src/app/page.tsx, src/components/home/Best.tsx, src/components/home/MainBanner.tsx
- #12
- 컴포넌트만 우선적으로 생성
- 더미 데이터로 리스트 생성
=> feat: 카드 리스트 컴포넌트 생성

package.json, src/app/page.tsx, src/components/home/Best.tsx, src/components/home/MainBanner.tsx, src/components/home/ShopList.tsx, yarn.lock
- #16
- 메인 컴포넌트별로 구분
- 반응형으로 UI 구현중
=> feat: 내 주변 매장 카드 리스트 UI 변경중

src/app/community/[id]/page.tsx, src/app/community/page.tsx, src/components/community/Community.tsx, tsconfig.json
=> feat: 커뮤니티 기본 페이지 생성

src/app/assets/types/types.ts, src/app/community/detail/page.tsx, src/app/community/page.tsx, src/app/community/write/page.tsx
=>  feat :커뮤니티 디테일 및 전체 css수정(#18)

src/app/community/write/page.tsx
=> feat:커뮤니티 알림창 수정

src/app/community/write/page.tsx, src/components/detail/DoneAssess.tsx
=> feat:write페이지 Link 수정

src/app/community/page.tsx, src/app/mypage/edit/page.tsx
=> feat: 커밋 작업저장

package.json, src/components/map/ColumnSlide.tsx, tailwind.config.ts, yarn.lock
=> feat: 맵으로 보기 스크롤 현상 제거

src/app/community/detail/[id]/page.tsx, src/app/community/page.tsx, src/components/community/BestPost.tsx, src/components/community/CategoryBtn.tsx, src/components/community/Daetgle.tsx, src/components/mypage/PostCard.tsx
=> feat:커뮤니티 css수정

package.json, src/app/NewProvider.tsx, src/app/layout.tsx, src/components/detail/Hoogi.tsx, src/components/home/Best.tsx, src/components/home/GoodPrice.tsx, src/components/home/NowLocationBtn.tsx, src/components/home/SearchForm.tsx, src/components/home/ShopCard.tsx, src/components/home/ShopCard2.tsx, src/components/map/ShopCard2.tsx, yarn.lock
=> feat:토스티파이 메인 카드들 자동 오픈

src/app/community/page.tsx, src/app/community/write/page.tsx
- #18 
-  커뮤니티 write 페이지 css 수정
=> feat:커뮤니티 write css 수정

src/app/community/page.tsx, src/components/mypage/PostCard.tsx
=> feat: 커뮤니티 게시글 두 줄로 변경 & 길이조정 & 게시글 구분선 추가

src/app/community/page.tsx, src/app/community/write/page.tsx, src/components/community/Daetgle.tsx, src/components/community/UpdateModal.tsx
=> feat: 커뮤니티 페이지네이션 완성 추가 수정 페이지에서 전체모음 카테고리 삭제 

src/app/community/detail/[id]/page.tsx, src/app/page.tsx, src/components/community/Community.tsx, src/components/community/CuteHeart.tsx, src/components/community/Daetgle.tsx, src/components/home/ShopList.tsx, src/components/home/UpButton.tsx
- #87
- 메인 페이지 top 버튼 구현
- 커뮤니티 상세 페이지 반응형 구현중
=> feat: 메인 페이지 top버튼 구현, 커뮤니티 상세 페이지 css

src/app/community/write/page.tsx, src/app/join/page.tsx, src/app/login/page.tsx, src/components/community/Daetgle.tsx, src/components/detail/DoneAssess.tsx, src/components/detail/Hoogi.tsx, src/components/home/NowLocationBtn.tsx, src/components/home/SearchForm.tsx, src/components/layout/Header.tsx
=> feat: alert창으로 표시되는 안내 메시지들 toastUI으로 메시지 표시될 수 있게 변경 완료

src/app/community/write/page.tsx, src/components/community/Daetgle.tsx
=> feat: 커뮤니티 댓글 css 수정

src/app/layout.tsx
=> feat: OG_image 수정 및 meta 오류 메시지 수정 완료 

src/app/community/page.tsx, src/app/mypage/edit/delete/page.tsx, src/app/mypage/page.tsx, src/components/community/CuteHeart.tsx, src/components/community/Daetgle.tsx, src/components/home/ShopCard.tsx, src/components/home/ShopList.tsx, src/components/home/home.css, src/components/layout/Header.tsx, src/components/mypage/PostCard.tsx, src/components/mypage/PostsDataOff.tsx
=> feat: 메인 & 커뮤니티 & 마이페이지 등 1차적인 반응형 UI 구현

src/app/community/page.tsx, src/components/community/CuteHeart.tsx, src/components/mypage/PostCard.tsx, src/components/mypage/PostsDataOff.tsx
=> feat: 커뮤니티 실시간 게시글 & 마이페이지 게시글 반응형 구현 

src/app/NewProvider.tsx, src/app/api/auth/[...nextauth]/route.ts, src/app/login/page.tsx, src/components/home/Best.tsx, src/components/home/GoodPrice.tsx, src/components/home/ShopList.tsx, src/components/layout/Footer.tsx
=> feat: 메인 페이지 반응형 구현 & 카카오 로그인 1차 구현

src/components/detail/ResultBar.tsx
=> feat: 중간 커밋

src/components/layout/Header.tsx
=> feat: 모바일 헤더 포지션 수정

src/app/mypage/page.tsx, src/components/layout/Header.tsx
=> feat: 소소하게 반응형 수정중

src/app/community/detail/[id]/page.tsx, src/app/community/write/page.tsx, src/app/join/page.tsx, src/components/community/DaetgleCard.tsx, src/components/community/UpdateModal.tsx, src/components/mypage/CommentsDataOff.tsx, src/components/mypage/PostCard.tsx
=> feat: 구현되지 못 했던 반응형 UI 부분 구현

src/components/community/Daetgle.tsx, src/components/detail/ImagePage.tsx
=> feat: 로드뷰 에러 해결

src/app/globals.css, src/components/home/ShopList.tsx, src/components/home/UpButton.tsx, src/components/layout/Header.tsx
=> feat: 디자인 디테일 디벨롭

src/components/home/SearchForm.tsx
=> feat: css 수정
